//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.02 at 12:22:48 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.jeejava.com/UserService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.jeejava.jaxb;
